# GENERATED by fourier/arbmodel.py from model/tp06_18d.py (SHA-256 76f7466a81d9498dd2d9b8d139f2c48667b7e33fad2c35a5eb61ab62f00620b9).
# Do not edit by hand: run `python3 fourier/arbmodel.py --generate` and review the diff against the reference.
#
# The only change from the reference is to its NUMBER tokens, in place, one token at a time:
#   a literal containing '.', 'e' or 'E'  ->  _D('<literal>'), a complex ball containing that exact decimal;
#   any other integer literal             ->  _I(<literal>), the exact integer as a complex ball;
#   an integer literal right after '**'   ->  unchanged (an exact Python int exponent).
# _D and _I are supplied by arbmodel.py, which executes this file only after checking that it equals a fresh
# generation from the reference. Every other token, comment and line break below is the reference's own.

"""Reference translation of fun_eval in Erhardt's TP06_18d_endo_bif.m.

Source: github.com/andreerhardt/cardiac-dynamics-of-a-human-ventricular-tissue-model-with-focus-on-early-afterdepolarizations
commit dc78f86fd218418e029ec43d945bcd0fc54b9f1e, file "bifurcation analysis/TP06_18d_endo_bif.m",
SHA-256 a50f6c08b4360dd257cce389a39ae72fda51e3642641bf5b8e5fced6c2225670 (MIT License, A. H. Erhardt).
The model is the ten Tusscher-Panfilov 2006 endocardial cell with K_i held fixed (a parameter) and the
Heaviside switch at V = -40 mV in the h and j rates replaced by u = 1/(1+exp(-5(V+40))).

The functions are written against a small namespace `M` (exp, log, sqrt) so the same text evaluates in
floats (math), numpy or mpmath. MATLAB precedence is kept: a/(b)^2 means a/(b^2).

State order (MATLAB kmrgd(1..18)): V, Xr1, Xr2, Xs, m, h, j, d, f, f2, fCass, s, r, R', Ca_i, Ca_sr, Ca_ss, Na_i.
"""
import math

NAMES = ["V", "Xr1", "Xr2", "Xs", "m", "h", "j", "d", "f", "f2", "fCass", "s", "r", "Rp",
         "Ca_i", "Ca_sr", "Ca_ss", "Na_i"]

# Parameters of the certified point (handoff 2026-09-30): Erhardt's reduced-repolarization setting.
PARAMS = dict(g_Kr=_D('0.0153'), g_Ks=_D('0.0275'), g_Na=_D('14.838'), g_K1=_D('5.405'), g_CaL=_D('0.000199'), Cm=_D('1.0'), K_i=_D('138.3'))


def field(x, p=PARAMS, M=math, i_stim=_D('0.0')):
    """Right-hand side dx/dt in mV/ms and mM/ms; x is a sequence of 18 numbers."""
    exp, log, sqrt = M.exp, M.log, M.sqrt
    V, Xr1, Xr2, Xs, m, h, j, d, f, f2, fCass, s, r, Rp, Ca_i, Ca_sr, Ca_ss, Na_i = x
    g_Kr, g_Ks, g_Na, g_K1, g_CaL, Cm, K_i = (p[k] for k in ("g_Kr", "g_Ks", "g_Na", "g_K1", "g_CaL", "Cm", "K_i"))
    R = _D('8314.472'); T = _I(310); FF = _D('96485.3415'); V_c = _D('0.016404'); P_kna = _D('0.03'); g_bna = _D('0.00029'); g_bca = _D('0.000592')
    g_to = _D('0.073'); g_pCa = _D('0.1238'); g_pK = _D('0.0146'); K_o = _D('5.4'); Na_o = _I(140); K_pCa = _D('0.0005'); P_NaK = _D('2.724')
    K_mk = _I(1); K_mNa = _I(40); K_NaCa = _I(1000); K_sat = _D('0.1'); alpha_0 = _D('2.5'); gamma_0 = _D('0.35'); Km_Ca = _D('1.38')
    Km_Nai = _D('87.5'); Ca_o = _I(2); k1_prime = _D('0.15'); k2_prime = _D('0.045'); k3 = _D('0.06'); k4 = _D('0.005'); EC = _D('1.5')
    max_sr = _D('2.5'); min_sr = _I(1); V_rel = _D('0.102'); V_xfer = _D('0.0038'); K_up = _D('0.00025'); V_leak = _D('0.00036')
    Vmax_up = _D('0.006375'); Buf_c = _D('0.2'); K_buf_c = _D('0.001'); Buf_sr = _I(10); K_buf_sr = _D('0.3'); Buf_ss = _D('0.4')
    K_buf_ss = _D('0.00025'); V_sr = _D('0.001094'); V_ss = _D('0.00005468')
    RTF = R * T / FF
    E_Na = RTF * log(Na_o / Na_i)
    E_K = RTF * log(K_o / K_i)
    E_Ks = RTF * log((K_o + P_kna * Na_o) / (K_i + P_kna * Na_i))
    E_Ca = _D('0.5') * RTF * log(Ca_o / Ca_i)
    alpha_K1 = _D('0.1') / (_I(1) + exp(_D('0.06') * (V - E_K - _I(200))))
    beta_K1 = (_I(3) * exp(_D('0.0002') * (V - E_K + _I(100))) + exp(_D('0.1') * (V - E_K - _I(10)))) / (_I(1) + exp(-_D('0.5') * (V - E_K)))
    xK1_inf = alpha_K1 / (alpha_K1 + beta_K1)
    i_K1 = g_K1 * xK1_inf * sqrt(K_o / _D('5.4')) * (V - E_K)
    i_Kr = g_Kr * sqrt(K_o / _D('5.4')) * Xr1 * Xr2 * (V - E_K)
    xr1_inf = _I(1) / (_I(1) + exp((-_I(26) - V) / _I(7)))
    tau_xr1 = (_I(450) / (_I(1) + exp((-_I(45) - V) / _I(10)))) * (_I(6) / (_I(1) + exp((V + _I(30)) / _D('11.5'))))
    xr2_inf = _I(1) / (_I(1) + exp((V + _I(88)) / _I(24)))
    tau_xr2 = (_I(3) / (_I(1) + exp((-_I(60) - V) / _I(20)))) * (_D('1.12') / (_I(1) + exp((V - _I(60)) / _I(20))))
    i_Ks = g_Ks * Xs ** 2 * (V - E_Ks)
    xs_inf = _I(1) / (_I(1) + exp((-_I(5) - V) / _I(14)))
    tau_xs = (_I(1400) / sqrt(_I(1) + exp((_I(5) - V) / _I(6)))) * (_I(1) / (_I(1) + exp((V - _I(35)) / _I(15)))) + _I(80)
    i_Na = g_Na * m ** 3 * h * j * (V - E_Na)
    m_inf = _I(1) / (_I(1) + exp((-_D('56.86') - V) / _D('9.03'))) ** 2
    tau_m = (_I(1) / (_I(1) + exp((-_I(60) - V) / _I(5)))) * (_D('0.1') / (_I(1) + exp((V + _I(35)) / _I(5))) + _D('0.1') / (_I(1) + exp((V - _I(50)) / _I(200))))
    v_inf = _I(1) / (_I(1) + exp((V + _D('71.55')) / _D('7.43'))) ** 2
    u = _I(1) / (_I(1) + exp(-_I(5) * (V + _I(40))))
    ah = (_I(1) - u) * _D('0.057') * exp(-(V + _I(80)) / _D('6.8'))
    bh = _D('0.77') / (_D('0.13') * (_I(1) + exp(-(V + _D('10.66')) / _D('11.1')))) * u + (_I(1) - u) * (_D('2.7') * exp(_D('0.079') * V) + _D('3.1e5') * exp(_D('0.3485') * V))
    tau_h = _I(1) / (ah + bh)
    aj = (_I(1) - u) * ((-_D('2.5428e4') * exp(_D('0.2444') * V) - _D('6.948e-6') * exp(-_D('0.04391') * V)) * (V + _D('37.78')) / (_I(1) + exp(_D('0.311') * (V + _D('79.23')))))
    bj = _D('0.6') * exp(_D('0.057') * V) / (_I(1) + exp(-_D('0.1') * (V + _I(32)))) * u + (_I(1) - u) * (_D('0.02424') * exp(-_D('0.01052') * V) / (_I(1) + exp(-_D('0.1378') * (V + _D('40.14')))))
    tau_J = _I(1) / (aj + bj)
    i_b_Na = g_bna * (V - E_Na)
    z = _I(2) * (V - _I(15)) / RTF  # GHK exponent; removable singularity at V = 15 mV
    i_CaL = g_CaL * d * f * f2 * fCass * _I(4) * (V - _I(15)) * FF / RTF * (_D('0.25') * Ca_ss * exp(z) - Ca_o) / (exp(z) - _I(1))
    d_inf = _I(1) / (_I(1) + exp((-_I(8) - V) / _D('7.5')))
    tau_d = (_D('1.4') / (_I(1) + exp((-_I(35) - V) / _I(13))) + _D('0.25')) * (_D('1.4') / (_I(1) + exp((V + _I(5)) / _I(5)))) + _I(1) / (_I(1) + exp((_I(50) - V) / _I(20)))
    f_inf = _I(1) / (_I(1) + exp((V + _I(20)) / _I(7)))
    tau_f = _D('1102.5') * exp(-(V + _I(27)) ** 2 / _I(225)) + _I(200) / (_I(1) + exp((_I(13) - V) / _I(10))) + _I(180) / (_I(1) + exp((V + _I(30)) / _I(10))) + _I(20)
    f2_inf = _D('0.67') / (_I(1) + exp((V + _I(35)) / _I(7))) + _D('0.33')
    tau_f2 = _I(600) * exp(-(V + _I(25)) ** 2 / _I(170)) + _I(31) / (_I(1) + exp((_I(25) - V) / _I(10))) + _I(16) / (_I(1) + exp((V + _I(30)) / _I(10)))
    fCass_inf = _D('0.6') / (_I(1) + (Ca_ss / _D('0.05')) ** 2) + _D('0.4')
    tau_fCass = _I(80) / (_I(1) + (Ca_ss / _D('0.05')) ** 2) + _I(2)
    i_b_Ca = g_bca * (V - E_Ca)
    i_to = g_to * r * s * (V - E_K)
    s_inf = _I(1) / (_I(1) + exp((V + _I(28)) / _I(5)))
    tau_s = _I(1000) * exp(-(V + _I(67)) ** 2 / _I(1000)) + _I(8)
    r_inf = _I(1) / (_I(1) + exp((_I(20) - V) / _I(6)))
    tau_r = _D('9.5') * exp(-(V + _I(40)) ** 2 / _I(1800)) + _D('0.8')
    i_NaK = P_NaK * K_o / (K_o + K_mk) * Na_i / (Na_i + K_mNa) / (_I(1) + _D('0.1245') * exp(-_D('0.1') * V / RTF) + _D('0.0353') * exp(-V / RTF))
    i_NaCa = K_NaCa * (exp(gamma_0 * V / RTF) * Na_i ** 3 * Ca_o - exp((gamma_0 - _I(1)) * V / RTF) * Na_o ** 3 * Ca_i * alpha_0) / (
        (Km_Nai ** 3 + Na_o ** 3) * (Km_Ca + Ca_o) * (_I(1) + K_sat * exp((gamma_0 - _I(1)) * V / RTF)))
    i_p_Ca = g_pCa * Ca_i / (Ca_i + K_pCa)
    i_p_K = g_pK * (V - E_K) / (_I(1) + exp((_I(25) - V) / _D('5.98')))
    kcasr = max_sr - (max_sr - min_sr) / (_I(1) + (EC / Ca_sr) ** 2)
    k1 = k1_prime / kcasr
    k2 = k2_prime * kcasr
    O = k1 * Ca_ss ** 2 * Rp / (k3 + k1 * Ca_ss ** 2)
    i_rel = V_rel * O * (Ca_sr - Ca_ss)
    i_up = Vmax_up / (_I(1) + K_up ** 2 / Ca_i ** 2)
    i_leak = V_leak * (Ca_sr - Ca_i)
    i_xfer = V_xfer * (Ca_ss - Ca_i)
    Ca_i_bufc = _I(1) / (_I(1) + Buf_c * K_buf_c / (Ca_i + K_buf_c) ** 2)
    Ca_sr_bufsr = _I(1) / (_I(1) + Buf_sr * K_buf_sr / (Ca_sr + K_buf_sr) ** 2)
    Ca_ss_bufss = _I(1) / (_I(1) + Buf_ss * K_buf_ss / (Ca_ss + K_buf_ss) ** 2)
    return [
        -(i_K1 + i_to + i_Kr + i_Ks + i_CaL + i_NaK + i_Na + i_b_Na + i_NaCa + i_b_Ca + i_p_K + i_p_Ca - i_stim) / Cm,
        (xr1_inf - Xr1) / tau_xr1,
        (xr2_inf - Xr2) / tau_xr2,
        (xs_inf - Xs) / tau_xs,
        (m_inf - m) / tau_m,
        (v_inf - h) / tau_h,
        (v_inf - j) / tau_J,
        (d_inf - d) / tau_d,
        (f_inf - f) / tau_f,
        (f2_inf - f2) / tau_f2,
        (fCass_inf - fCass) / tau_fCass,
        (s_inf - s) / tau_s,
        (r_inf - r) / tau_r,
        -k2 * Ca_ss * Rp + k4 * (_I(1) - Rp),
        Ca_i_bufc * ((i_leak - i_up) * V_sr / V_c + i_xfer - Cm * (i_b_Ca + i_p_Ca - _I(2) * i_NaCa) / (_I(2) * V_c * FF)),
        Ca_sr_bufsr * (i_up - (i_rel + i_leak)),
        Ca_ss_bufss * (-Cm * i_CaL / (_I(2) * V_ss * FF) + i_rel * V_sr / V_ss - i_xfer * V_c / V_ss),
        -Cm * (i_Na + i_b_Na + _I(3) * i_NaK + _I(3) * i_NaCa) / (V_c * FF),
    ]
